#!/usr/bin/env python3
from __future__ import annotations

import argparse
from copy import deepcopy
from ipaddress import ip_address, ip_network
from pathlib import Path
from typing import Any

from backend_common import load_json, slug, write_json


DEFAULT_MHBENCH_VM_TYPE = "ubuntu_base_running"
DEFAULT_MHBENCH_FLAVOR = "m1.small"
DEFAULT_DNS_SERVERS = ["8.8.8.8"]
GENERATED_DIR = Path(__file__).resolve().parents[1] / "generated"


def build_mhbench_spec(environment: dict[str, Any], *, name: str | None = None) -> dict[str, Any]:
    env_name = slug(name or environment.get("name") or "cyblocks-environment")
    hosts_by_id = {host["id"]: host for host in environment.get("hosts", [])}
    subnets = []

    for network in environment.get("networks", []):
        subnet_hosts = []
        for member in network.get("members", []):
            if member.get("kind") != "host":
                continue
            host = hosts_by_id.get(member.get("id"))
            if not host:
                continue
            subnet_hosts.append(
                {
                    "name": host["hostname"],
                    "vm_type": host.get("vmType") or DEFAULT_MHBENCH_VM_TYPE,
                    "flavor": host.get("flavor") or DEFAULT_MHBENCH_FLAVOR,
                    "ip_address": member.get("ipAddress") or host.get("ipAddresses", {}).get(network["id"]),
                }
            )

        subnets.append(
            {
                "name": network["id"],
                "cidr": network["cidr"],
                "dns_servers": network.get("dnsServers") or DEFAULT_DNS_SERVERS,
                "hosts": subnet_hosts,
            }
        )

    return {
        "name": env_name,
        "networks": [
            {
                "name": f"{env_name}_network",
                "description": "Generated by Cyblocks for MHBench/OpenStack handoff.",
                "subnets": subnets,
            }
        ],
        "subnet_connections": [
            {
                "from_subnet": connection["fromSubnet"],
                "to_subnet": connection["toSubnet"],
                "protocol": None if connection.get("protocol") == "any" else connection.get("protocol"),
                "ports": connection.get("ports"),
                "bidirectional": connection.get("bidirectional", True),
            }
            for connection in environment.get("subnetConnections", [])
        ],
        "playbooks": deepcopy(environment.get("playbooks", [])),
    }


def validate_mhbench_spec(spec: dict[str, Any]) -> list[str]:
    errors = []
    if not str(spec.get("name") or "").strip():
        errors.append("Spec is missing a name.")

    networks = spec.get("networks")
    if not isinstance(networks, list) or not networks:
        errors.append("Spec must contain at least one network.")
        networks = []

    subnet_names = set()
    host_names = set()
    subnet_ranges = {}
    for network_index, network in enumerate(networks):
        subnets = network.get("subnets")
        if not isinstance(subnets, list):
            errors.append(f"Network {network_index}: subnets must be an array.")
            continue

        for subnet_index, subnet in enumerate(subnets):
            subnet_name = str(subnet.get("name") or "").strip()
            if not subnet_name:
                errors.append(f"Network {network_index} subnet {subnet_index}: missing name.")
                continue
            if subnet_name in subnet_names:
                errors.append(f"Duplicate subnet name {subnet_name!r}.")
            subnet_names.add(subnet_name)

            try:
                subnet_range = ip_network(str(subnet.get("cidr")), strict=False)
                subnet_ranges[subnet_name] = subnet_range
            except ValueError as exc:
                errors.append(f"Subnet {subnet_name}: invalid cidr: {exc}.")
                subnet_range = None

            hosts = subnet.get("hosts", [])
            if not isinstance(hosts, list):
                errors.append(f"Subnet {subnet_name}: hosts must be an array.")
                continue
            for host_index, host in enumerate(hosts):
                host_name = str(host.get("name") or "").strip()
                if not host_name:
                    errors.append(f"Subnet {subnet_name} host {host_index}: missing name.")
                elif host_name in host_names:
                    errors.append(f"Duplicate host name {host_name!r}.")
                host_names.add(host_name)

                if not str(host.get("vm_type") or "").strip():
                    errors.append(f"Host {host_name or host_index}: missing vm_type.")
                if not str(host.get("flavor") or "").strip():
                    errors.append(f"Host {host_name or host_index}: missing flavor.")

                if host.get("ip_address") and subnet_range:
                    try:
                        address = ip_address(str(host["ip_address"]))
                    except ValueError as exc:
                        errors.append(f"Host {host_name or host_index}: invalid ip_address: {exc}.")
                        continue
                    if address not in subnet_range:
                        errors.append(f"Host {host_name or host_index}: ip_address {address} is outside {subnet_range}.")

    for index, connection in enumerate(spec.get("subnet_connections", [])):
        from_subnet = connection.get("from_subnet")
        to_subnet = connection.get("to_subnet")
        if from_subnet not in subnet_names:
            errors.append(f"Subnet connection {index}: unknown from_subnet {from_subnet!r}.")
        if to_subnet not in subnet_names:
            errors.append(f"Subnet connection {index}: unknown to_subnet {to_subnet!r}.")
        if from_subnet == to_subnet:
            errors.append(f"Subnet connection {index}: from_subnet and to_subnet must differ.")

    for index, playbook in enumerate(spec.get("playbooks", [])):
        if not isinstance(playbook, dict):
            errors.append(f"Playbook {index}: expected object.")
            continue
        if not str(playbook.get("name") or "").strip():
            errors.append(f"Playbook {index}: missing name.")
        if not isinstance(playbook.get("args", {}), dict):
            errors.append(f"Playbook {index}: args must be an object.")

    return errors


def export_mhbench_spec(
    environment: dict[str, Any],
    *,
    out: Path | None = None,
    mhbench_root: Path | None = None,
    name: str | None = None,
) -> tuple[dict[str, Any], Path]:
    spec = build_mhbench_spec(environment, name=name)
    errors = validate_mhbench_spec(spec)
    if errors:
        raise ValueError("; ".join(errors))
    output_path = resolve_output_path(spec["name"], out=out, mhbench_root=mhbench_root)
    write_json(output_path, spec)
    return spec, output_path


def resolve_output_path(name: str, *, out: Path | None = None, mhbench_root: Path | None = None) -> Path:
    if out:
        return out
    if mhbench_root:
        return mhbench_root / "environments" / "generated" / f"{name}.json"
    return GENERATED_DIR / f"{name}.mhbench.json"


def main() -> None:
    parser = argparse.ArgumentParser(description="Export a Cyblocks intermediate DSL as an MHBench environment JSON.")
    parser.add_argument("input", type=Path, help="Cyblocks intermediate DSL JSON")
    parser.add_argument("--out", type=Path, help="Output MHBench environment JSON path")
    parser.add_argument("--mhbench-root", type=Path, help="Write into MHBench/environments/generated")
    parser.add_argument("--name", help="Override exported topology name")
    parser.add_argument("--validate-only", action="store_true", help="Validate without writing a file")
    args = parser.parse_args()

    spec = build_mhbench_spec(load_json(args.input), name=args.name)
    errors = validate_mhbench_spec(spec)
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        raise SystemExit(1)

    if args.validate_only:
        print("Validation passed.")
        return

    output_path = resolve_output_path(spec["name"], out=args.out, mhbench_root=args.mhbench_root)
    write_json(output_path, spec)
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
